### ISSUE TITLE
项目中加入TFPopup文件，未使用，崩溃了

### ISSUE THREAD

**Issue by dagundejuzi** [shmxybfq/TFPopup#10]
断点崩在 UIScrollView+TFPopup.m  文件的belongToPopupView方法中，堆栈看是因为循环了，一直调用了这个方法。

**Comment by shmxybfq** [comment]
是用pod导入的吗？建议现在先用pod导入，因为现在在开发拖动功能，代码直接提交到master上，如果直接导入代码的话会把现在正在开发的代码同时导进去，大概这周可以吧拖动功能完成，不影响已有功能。

**Comment by shmxybfq** [comment]
> 断点崩在 UIScrollView+TFPopup.m 文件的belongToPopupView方法中，堆栈看是因为循环了，一直调用了这个方法。

使用pod导入了吗？我新提交了代码去掉了拖动代码，不会再崩溃了

**Comment by dagundejuzi** [comment]
@shmxybfq 没有使用pod，git拉下来之后，从demo里挖出的文件。

**Comment by dagundejuzi** [comment]
放测试项目里没崩了。

**Comment by shmxybfq** [comment]
使用pod是没问题的，pod的最新版本是稳定的版本，demo里的代码是正在开发的版本，不过昨天我已经去掉了影响使用的代码，现在直接用demo里的代码应该是没问题的，如果有问题随时反馈我随时改掉
