### ISSUE TITLE
弹框消失，不销毁的？

### ISSUE THREAD

**Issue by tanjieaa** [shmxybfq/TFPopup#2]
调用tf_hide或者tf_remove时，不走dealloc的，在您的demo好像也没走dealloc

**Comment by tanjieaa** [comment]
AlertNormal不会销毁，BlankView会销毁

**Comment by shmxybfq** [comment]
感谢反馈，我修改一下

**Comment by Sniper-xu** [comment]
TFPopupProtocol.h 是打算干嘛的？

**Comment by shmxybfq** [comment]
不会销毁的bug已经修改了，主要三个原因：1、调用的时候弹框点击的block引用了自己导致循环引用2、动画的代理引用了弹框3、mask动画的代理引用了弹框

**Comment by shmxybfq** [comment]
TFPopupProtocol 已经删除了，以前版本用来拆分协议的类，后来直接写到了分类里
