### ISSUE TITLE
希望添加动画的延时属性

### ISSUE THREAD

**Issue by dagundejuzi** [shmxybfq/TFPopup#6]
在extension中有看到延时属性，但是param中没有，所以我尝试了下在param 添加属性，在UIView+TFPopup.m 文件的```tf_reload```方法中将值传给extension。
![image](https://user-images.githubusercontent.com/16382880/59823928-4b3edd80-9362-11e9-8c36-8754dd44e9ee.png)
但是在```tf_show```方法中，```self.extension.showAnimationDelay```的值依然为0。
打印```self.extension```对象，在```tf_reload```和```tf_show```方法中，它是同一个。请问怎样才能把值传给extension呢？作者可以加一个这个功能吗？

**Comment by shmxybfq** [comment]
多谢反馈~
动画延迟执行时间原来可以在代理TFPopupDataSource中设置，可以通过在弹框的本类或者子类中重写以下方法
【- (NSTimeInterval)tf_popupView:(UIView *)popup animationDelayForState:(TFPopupState)state;】
配置弹出和消失时的动画延迟执行时间。
![WechatIMG1519](https://user-images.githubusercontent.com/7427125/59893640-27d26c00-9410-11e9-8f47-c1383f999e50.jpeg)

同时为了方便起见，现在已经在动画参数中添加了两个属性来控制动画延迟：
@property(nonatomic,assign)NSTimeInterval showAnimationDelay;
@property(nonatomic,assign)NSTimeInterval hideAnimationDelay;
![WechatIMG1518](https://user-images.githubusercontent.com/7427125/59893625-1b4e1380-9410-11e9-9317-99c3f3ecea99.jpeg)

可以更新到最新版本使用，使用过程中如有任何问题，期待反馈~

**Comment by dagundejuzi** [comment]
@shmxybfq  谢谢！ 可以用了。
